spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyfarm?serverTimezone=Asia/Seoul
    username: user1
    password: 1234
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: 1234
      database: CloneMarket
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jwt:
    secret: HRlELXqpSB
server:
  host: localhost
  port: 9090
logging:
  level:
    org.apache.http: INFO
    httpclient.wire: INFO
sms:
  serviceId: ncp:sms:kr:303378693701:clonemarket
  accessKey: hUpV911uJ8qDRF951RYx
  secretKey: 38kGXq9twml9AQDGuHWrLDXt61Cx75Pj9YeHnmhW
file:
  upload:
    path: C:\Users\hhh73\StudioProjects\CloneMarket-202303\API\src\main\resources\static\profile