spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyfarm?serverTimezone=Asia/Seoul
    username: 
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jwt:
    secret: 
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  host: localhost
  port: 9090
logging:
  level:
    org.apache.http: INFO
    httpclient.wire: INFO
sms:
  serviceId: 
  accessKey: 
  secretKey: 
file:
  upload:
    path: C:\Users\hhh73\StudioProjects\CloneMarket-202303\API\src\main\resources\static\profile
security:
  authorization: 'enabled'
